import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './assets/css/globals.css'
import Navbar from './components/Layouts/Navbar'
import Footer from './components/Layouts/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Template',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`flex flex-col h-screen bg-white text-narmal dark:bg-gray-900 dark:text-white ${inter.className}`}
      >
        <Navbar />
        <main className='flex-1 overflow-y-auto'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
