import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StoreProvider from '@/app/store/StoreProvider'
import '@/app/assets/css/globals.css'
import Navbar from '@/app/components/Layouts/Navbar'
import Footer from '@/app/components/Layouts/Footer'
import Providers from '@/app/[locale]/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Template',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`flex flex-col h-screen bg-gray-50 text-narmal dark:bg-gray-800 dark:text-white ${inter.className}`}
      >
        <Providers>
          <Navbar />
          <main className='flex-1'>
            <StoreProvider>{children}</StoreProvider>
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
